config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index', as: 'home'

  post 'check_card', to: 'cards#check_card'

  resources :cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  before_validation :review_date_change

  validates :original_text, :translated_text, presence: true,
                                              length: { minimum: 2 }
  validates :review_date, presence: true

  validate :original_and_translated_not_equal

  scope :for_review, -> { where('review_date <= ?', Date.today) }

  private

  def original_and_translated_not_equal
    return unless original_text == translated_text
    errors.add(:original_text, "can't be equal")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :card, only: %i[show edit update destroy]

  def index
    @cards = Card.all
  end

  def show; end

  def new
    @card = Card.new
  end

  def edit; end

  def create
    card = Card.new(card_params)

    if card.save
      redirect_to card
    else
      render 'new'
    end
  end

  def update
    if card.update(card_params)
      redirect_to card
    else
      render 'edit'
    end
  end

  def destroy
    card.destroy

    redirect_to cards_path
  end

  def check_card
    card_id = params[:card_values][:card_id]
    text_for_review = params[:card_values][:original_text]

    if CardReviewService.new(card_id, text_for_review).call
      flash[:notice] = 'You guessed!'
    else
      flash[:notice] = 'nope'
    end

    redirect_to home_path
  end

  private

  def card
    @card ||= Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @card = Card.for_review.sample
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/_form.html.erb
<%= form_with model: @card, local: true do |form| %>

  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :original_text %><br>
    <%= form.text_field :original_text %>
  </p>

  <p>
    <%= form.label :translated_text %><br>
    <%= form.text_field :translated_text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Original</th>
    <th>Translated</th>
    <th></th>
  </tr>

  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime('%d-%m-%Y') %></td>
      <td><%= link_to 'Show', card_path(card) %></td>
      <td><%= link_to 'Edit', edit_card_path(card) %></td>
      <td><%= link_to 'Destroy', card_path(card),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p>
  <strong>Original:</strong>
  <%= @card.original_text %>
</p>

<p>
  <strong>Translated:</strong>
  <%= @card.translated_text %>
</p>

app/views/home/index.html.erb
<h1>Первый в мире удобный менеджер флеш-карточек. Именно так.</h1>

<%= @card.translated_text %>
<%= @card.id %>
<%= simple_form_for(:card_values, method: :post, url: check_card_path) do |f| %>
  <%= f.input :card_id, input_html: { value: @card.id }, as: :hidden %>
  <%= f.input :original_text %>
  <%= f.submit 'Check' %>
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <span class="navbar-brand"><%= link_to 'Флэшкарточкер', home_path %></span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <span class="nav-link"><%= link_to 'Все карточки', cards_path %></span>
          </li>
          <li class="nav-item">
            <span class="nav-link"><%= link_to 'Добавить карточку', new_card_path %></span>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-primary" role="alert" id="notice"><%= notice %></p>
    <% end %>
   
    <%= yield %>
  </body>
</html>